### ISSUE TITLE
SSO commit

### ISSUE THREAD

**Issue by shaidar** [mitodl/edx-platform#207] opened 2020-11-16 17:34 UTC
>  Removing code that blocks login on SSO accounts.

> There was a commit that was intended to address user accounts that were disabled that breaks login for accounts that are SSO only. Deleting that code to restore functionality on our residential deployment.

Below is the single SSO commit in `mitx/juniper` that needs to be submitted on the `mitx/koa` branch:
```
5c1d51f3c7e0b255647bdf5e1a6e2656627ec53f	Removing code that blocks login on SSO accounts
```

I believe this issue must have been fixed upstream in koa. If not, we should do the following:

- [x] PR merged into [mitx/koa branch](https://github.com/mitodl/edx-platform/tree/mitx/koa)
- [x] PR merged into [xpro/koa branch](https://github.com/mitodl/edx-platform/tree/xpro/koa)
- [ ] ~~upstream PR merged to [edx-platform/master](https://github.com/edx/edx-platform/tree/master)~~

**Comment by HamzaIbnFarooq** [comment] 2020-11-17 13:58
I have created two PRs https://github.com/mitodl/edx-platform/pull/215 , https://github.com/mitodl/edx-platform/pull/216 for this fix.

**Comment by HamzaIbnFarooq** [comment] 2020-11-17 14:22
In the commit message, it's being said that the check was meant to stop `Disabled Users` from getting logged in, while it clashed with SSO only user accounts. So, under this particular scenario removing that `validation check` will be a good solution but it will lose its feature of blocking disabled users.
So will it be good if rather than deleting that code block, we just replace `user.has_usable_password()` with `user.is_active`, in this way, I think it will be more acceptable to edx community.

**Comment by blarghmatey** [comment] 2020-11-17 14:38
I think that makes sense to me.

**Comment by pdpinch** [comment] 2020-11-17 15:23
@HamzaIbnFarooq that sounds like a good plan. If you can find out who made the commit at edX, it may make sense to reach out to them on edX slack, or tag them on the upstream PR. 

While I'm definitely interested in getting this upstreamed, it's lower priority than getting the good-enough commits merged in our branches.

**Comment by HamzaIbnFarooq** [comment] 2020-11-17 15:54
@pdpinch I have created an Upstream PR for this fix here (https://github.com/edx/edx-platform/pull/25611). The author of that commit is a colleague of mine from arbisoft, I will mention him on PR as well as get him in the loop over slack.

And obviously, I will keep it a low priority fix.

**Comment by HamzaIbnFarooq** [comment] 2020-11-18 07:05
@shaidar @blarghmatey do we have any use-case guide to execute and test this feature locally?

**Comment by blarghmatey** [comment] 2020-11-18 15:16
This one is hard to test locally as it requires having third party auth enabled which might be difficult to do in a local environment. I know that it works because we have been using it in production for our residential environment.

**Comment by pdpinch** [comment] 2020-11-18 19:19
Maybe we can reproduce it with one of the built-in SSOs, like Google or Apple?

**Comment by HamzaIbnFarooq** [comment] 2020-11-23 12:59
As per my understanding of edx's disable account feature, edx doesn't rely on the `User.is_active` state for disabling users, rather it changes the `user's password to a nonusable password` via using Django's `User.set_unusable_password`. So we can't really remove this SSO check from edx.
Here are two of the issues which confirm that this behavior is intended to be kept, as it is, in edx (https://openedx.atlassian.net/browse/EDUCATOR-2627 & https://openedx.atlassian.net/browse/LEARNER-6183)
cc: @pdpinch @shaidar @blarghmatey

**Comment by pdpinch** [comment] 2020-11-23 13:56
https://openedx.atlassian.net/browse/LEARNER-6183 seems to say that setting the password to "something unusable" was insufficient for blocking logging in via google. But I don't have access to the ticket that solved it, https://openedx.atlassian.net/browse/SEC-414#icft=SEC-414 

Thanks for looking into this further Hamza, but I think there's more research to be done. Do you happen to know anyone at Arbisoft that works on the sustaining team? They might have access to that security ticket.

**Comment by HamzaIbnFarooq** [comment] 2020-11-23 14:14
A couple of days back, I asked a colleague from edx to open that link but he was unable to do so, I will try getting someone else's help.
But as far as the solution of that issue is concerned the issue was solved by the same code which we want to remove (https://github.com/edx/edx-platform/pull/19807)

**Comment by shaidar** [comment] 2020-12-04 14:28
@pdpinch @blarghmatey Based on the info above, am I wrong in assuming that this most likely won't be upstreamed and we should close this issue?

**Comment by HamzaIbnFarooq** [comment] 2021-01-08 08:28
@pdpinch @blarghmatey I have tried testing this issue on both ironwood and koa using [SAMLtest](https://samltest.id/start-sp-test/) but couldn't reproduce the error on my local, users are getting registered and logged-in perfectly.

There might be some issue in SSO at a specific time-frame/commit, but now it doesn't seem to be hindering the registration and login process.

**Comment by pdpinch** [comment] 2021-01-11 02:16
@HamzaIbnFarooq when you use SAMLtest does it create a password for the user automatically? I think you had said that SAML can be configured to do that.

**Comment by HamzaIbnFarooq** [comment] 2021-01-11 03:34
@pdpinch Yes, the password was created automatically. We don't have to explicitly declare password creation somewhere, the SOCIAL_AUTH_PIPELINE takes care of that by itself.

**Comment by pdpinch** [comment] 2021-03-13 15:51
I'm closing this because we closed the upstream issue. 

We'll have to keep an eye on this with the Residential upgrade to Lilac to see if it's still an issue.

**Closed as completed by pdpinch** 2021-03-13 15:51 UTC
Labels: Koa, upstream
